### ISSUE TITLE
`Could not load the Qt platform plugin` while starting spinetoolbox

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1227]
This happens in some environments, the entire message is:

```
Could not load the Qt platform plugin "windows" in "" even though it was found. This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem. Available platform plugins are: direct2d, minimal, offscreen, windows.
```

Spine Toolbox doesn't launch. Seems related to conflicts between different packages using Qt.

**Comment by PekkaSavolainen** [comment]
The culprit here is the `pyqt` package that is installed when creating a 'regular' Anaconda environment. We've had a mention about the conflict between pyqt and pyside in our readme's troubleshooting section for a long time.

To recreate, you just need to install pyqt package from the **conda forge channel**.

```
conda install pyqt
```

This adds a `qt.conf` file to the environment root, which breaks our `PySide2` installed via pip. We could either tell users to delete this file from their environments, (which most likely breaks any packages that use the pyqt package in that environment) or keep using the commit above. If this fix causes any problems, we should remove it and tell them to install our app into a miniconda environment instead (like we already do).

**Comment by manuelma** [comment]
The warning in the README was ok, but far from being a real answer for some of our users I believe. I'm talking of users that are using conda for the first time, don't know how to remove/create/inspect environments, and will look somewhere else before any attempt at debugging. The fix in the above commit is a real solution that gets our users going without any effort from their part. I don't know how you @PekkaSavolainen managed to come up with it but I hope it's here to stay.
