### ISSUE TITLE
Ask before close for specifications that have been changed

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1236]
When closing e.g. importer specification with X from the upper right, Toolbox does not ask whether to save changes. This should take place. 

Should it confirm also when closing with 'cancel'?  Juha's view: no. User has already chosen to forgone changes.

Also a short-cut for closing with ok would be nice: ctrl-enter proposed.

Issue split from #1228, where there is bit more discussion.

**Comment by manuelma** [comment]
Something done here. Basically we now have a dialog that propose to save changes when quitting the form with a dirty spec. Ctrl+Enter also saves changes and closes.

Another important change, is that modifications to the spec are no longer part of the project undo stack. In other words, the user can't undo changes to the spec once the editor widget has been closed. I believe this is correct, because changes to the spec are saved to the spec file, *not* to the project file. I'm not sure why we wanted to be able to undo spec changes from the project? Maybe it was before we had undo/redo in the import editor?

This opens up the question, do we want undo/redo in the other spec editor widgets (Tool, and DT)? Perhaps yes, but not with a high priority in my opinion.

**Comment by soininen** [comment]
> This opens up the question, do we want undo/redo in the other spec editor widgets (Tool, and DT)? Perhaps yes, but not with a high priority in my opinion.

I think the behavior should be consistent accross the project items.
