### ISSUE TITLE
Should Exporter remove empty columns?

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1299]
Sometimes when using the exporter spec editor I end up having spaces in between my columns (because I decided to 'hide' a mapping suddenly, or I didn't get the numbers right). Should the writer remove those columns and yield a 'compact' table? It is the case for pivot rows I believe (if I map to pivot rows 1, 4, and 7, and don't 'receive' empty rows 2, 3, 5, and 6, right?).

**Comment by soininen** [comment]
I had plans on 'compacting' the mappings in the specification editor itself. Also, when inserting a new column (or moving an existing column) the other columns would make 'space'. Overall more dynamic column numbering. I just never got to implement it.

I am not a big fan of 'compacting' the table in the writer since you might actually want to have those empty columns/rows there.

**Comment by manuelma** [comment]
> I am not a big fan of 'compacting' the table in the writer

You're right, but we do compact the pivot rows in the writer, don't we?

But I agree with your idea of making the Spec editor smarter. I also think this is not urgent, we can do it whenever we get the chance.

**Comment by soininen** [comment]
> we do compact the pivot rows in the writer, don't we?

Oops, didn't remember we had that inconsistency there! I think it should not do auto-compact either. I like the low-level API to be simple and predictable.

**Comment by soininen** [comment]
There is now a Compact button that resolves this issue.
