### ISSUE TITLE
Exporter does not export multiple tables from same mapping

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1303]
In the attached example project mapping 'foo' is trying to export two tables. However, the resulting Excel file contains only one of them. I found this issue when working in another project with more tables.

[Minimal_for_issues.zip](https://github.com/Spine-project/Spine-Toolbox/files/6156075/Minimal_for_issues.zip)

**Comment by jkiviluo** [comment]
I split them into separate mappings, but still outputs only one. That was surprising.

**Comment by soininen** [comment]
The issue was that Excel writer was dropping sheets it thought it didn't write to. The heuristics to identify such sheets didn't work, though and so one of the sheets with actual data on it got dropped. I removed the sheet drop feature from the writer as it doesn't look like something we actually want to do. Hopefully Exporter works now as expected.

**Comment by jkiviluo** [comment]
Seems to be working. Thanks!
