### ISSUE TITLE
In order to refresh "Additional Program Files" or other code dependencies, the project must be reloaded

### ISSUE THREAD

**Issue by jimhommes** [Spine-project/Spine-Toolbox#1350]
I've attached an example project to recreate this here:
[refreshdependencies.zip](https://github.com/Spine-project/Spine-Toolbox/files/6241716/refreshdependencies.zip)

Code dependencies are not updated automatically. To recreate this take the following steps:

1. Run the tool in the project
2. Change the code of the testdependency.py, e.g. add a print statement to the initialization
3. Run again, and see that the print statement does not come through

This happens both when the tool is executed in "Work directory" and the dependencies are added as additional program files, and when executed in "Source directory" with the dependencies in the same directory.

There is no problem with editing the "Main program file", these changes come through immediately. 

The solution right now is to reload the project.

**Comment by manuelma** [comment]
Thanks @jimhommes 

I suspect the issue here might be that the program file needs to be saved independently of the tool spec. You are editing the code in the Tool specification editor? In that case, you need to press the save button that's below the editor. Are you doing it? It was very small a few commits ago, recently I make it bigger so people can actually notice it.

**Comment by jimhommes** [comment]
In the example project I edited the code (a bit quickly) through the tool editor and using the save button. In my other project I have the same problem and I'm using an external IDE there.

**Comment by PekkaSavolainen** [comment]
Confirmed. This only happens when running the tool in Python Console. It seems that IPython reserves the imports in memory for successive runs. Maybe there's a way to invalidate IPython's cache when running the same main file but when additional input files have changed.

**Comment by PekkaSavolainen** [comment]
> I suspect the issue here might be that the program file needs to be saved independently of the tool spec. 

I crawled through our ToolSpecificationEditor, ToolSpecifications, ToolInstances and updating the specification models code and I couldn't find anything wrong there. This happens with **Additional** Program Files in (Python) Console. Probably in Julia Console as well.

**Comment by PekkaSavolainen** [comment]
And to test you can just make this as main program file

```python
from function import print_something

print("Hello World")
print_something()
```

And this as additional program file.

```python
def print_something():
	print("hello from print something")
```

Now run this in Python Console once, then edit the print_something() function, and run again.

**Comment by soininen** [comment]
A workaround is to use `reload()` in the main program file:

```python
from importlib import reload
import function

reload(function)
function.print_something()
```

**Comment by PekkaSavolainen** [comment]
Thanks @soininen. I'm not sure if you tried this already but there is an IPython extension just for this purpose called `autoreload`. Ideal solution for this issue would be to start this autoreload extension at python console startup and all modules should be reloaded automatically. However, I'm having trouble with this extension. Just doing the example here (https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html) does not seem to work in our Python Console at all?! Can somebody else try it?

**Comment by manuelma** [comment]
> Ideal solution for this issue would be to start this autoreload extension at python console startup

- Does this mean that the user would need to restart the console after doing their changes in additional program files?
- I thought that restarting the console manually was already a work-around for this problem, is that not the case?

**Comment by PekkaSavolainen** [comment]
> Does this mean that the user would need to restart the console after doing their changes in additional program files?

No.

> I thought that restarting the console manually was already a work-around for this problem ... ?

I guess so, haven't tried it.

**Comment by PekkaSavolainen** [comment]
Ok, I got the `autoreload` extension working in Spine Toolbox. 

In summary, there are three things you can do to overcome this issue

**1.**
Restart the Python Console by using the context-menu (mouse right-click menu) between executions.

**2.**
Use the IPython autoreload extension.

Turns out my try yesterday failed due to a rookie user mistake. You need to execute the Python Tool in **Source directory** to apply the changes in additional files. 

Here are the steps to test it yourself:
1. Run a Python Tool first to make the Python Console appear
2. In the Python Console, first run command `%load_ext autoreload` and then a second command ``%autoreload 2`
3. Make changes to additional files
4. Run the Python Tool a second time to confirm that the changes were applied

Of course, at the moment, this autoreload extension needs to be loaded for each Python Console separately. There are corner cases where it does not always work (see autoreload docs if interested).

**3.**
Use the `reload()` approach, suggested by @soininen above

We should consider giving the users the option of loading this `autoreload` extension automatically in Tool properties in later versions.

**Comment by PekkaSavolainen** [comment]
TBC in #1357.
