### ISSUE TITLE
Refactor main toolbar to show specs inline

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1373]
I'm not too happy with the drop down menu we use to show item specs. I think it would be better if the specs where shown directly in the toolbar, next to the corresponding 'base' item. There would also be a button to expand/collapse the list of specs.

I will give it a try.

**Comment by manuelma** [comment]
Done. Please let me know what you think.

If we don't like it, we just need to revert 5de92ef263ef24b7dbb0733d95104244f67c551a

**Comment by PekkaSavolainen** [comment]
I like it.

I was just going to comment that the submenu could use with a different shade of blue but after commit 4957ef6 it's perfect.

**Comment by PekkaSavolainen** [comment]
How about adding the number of specs to the main toolbar? Something like this:

![issue_1373](https://user-images.githubusercontent.com/43600314/114833260-0f4af700-9dd8-11eb-8a88-9386034dc888.png)

Just an idea. Not sure if it's a good one.

**Comment by soininen** [comment]
That little 'arrow' could change its direction when the specifications are in expanded state, e.g. from `>>` to `<<`.

**Comment by jkiviluo** [comment]
It's not immediately obvious to which symbol the small arrow belongs to. I don't know if it is due to icon picture size, but it looks like there is some extra room between the correct tool and the arrow. Maybe the icon paddings could be changed so that the arrow goes close to the right icon. I would also think that the space between icons is rather large because the icons take more space than necessary.

If you have a workflow with a lot of specifications for e.g. a tool, then expanding the icons on a small screen could mean that you don't see all of them. The good thing is that you can not expand and just drag a generic tool icon and then choose the spec. Maybe this is just something to be thought about in future.

**Comment by manuelma** [comment]
> then expanding the icons on a small screen could mean that you don't see all of them.

In my system, when that happens, an 'extension' button appears in the toolbar, so I can click and see a 'second row' of buttons. Isn't it the case for you?

**Comment by manuelma** [comment]
I think this is done. Any last words? I will update the changelog and then close.

Note that two features were added:
- Reorganize toolbar project item icons with drag and drop
- Color toolbar icons from Settings -> General

**Comment by PekkaSavolainen** [comment]
Fine by me.
