### ISSUE TITLE
spine_items update at startup causes second Toolbox to start while executing a project

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1377]
Reported by @jkiviluo 

If `spine_items` gets updated at Toolbox startup, a second Toolbox instance (with second Toolbox main window etc.) will launch during project execution when executing certain items such as Exporter or Importer. We should make sure no surprise Toolbox windows pop up on such occasions.

**Comment by PekkaSavolainen** [comment]
Nice catch. I just tried executing a project with three Importers and it opens three new Spine Toolboxes on top of the original one. :)

**Comment by PekkaSavolainen** [comment]
Quite interesting bug/feature here. I believe the reason here is the `ReturningProcess.run_until_complete()` methods `self.start()` line. In the normal case this should start the `ReturningProcess.run()` method. But when spine_items has been updated we start a new Spine Toolbox on top of the old one and when the execution gets to `self.start()`, it seems that this does not start `ReturningProcess.run()` but starts the `subprocess.run()` in main.py again. So, it somehow replaces the `run()` method.

My suggestion for the fix is to make users restart the app themselves. We can print something like this after spine_items has been upgraded. `Application is now up-to-date. Please restart Spine Toolbox.`

**Comment by manuelma** [comment]
That should be the easiest. Windows is not the best at forking apparently. Previously, we used to restart toolbox after items upgrade by using `os.execl` instead of `subprocess.run`. On Linux it worked flawlessly, but on Windows there was a delay where the user would typically restart toolbox themselves.

If we go with the 'please start toolbox again manually' option, we should do it only for Windows, and for Linux we can get back to auto-restart using `os.execl`.

But I would like to figure out the cause of the problem and fix it eventually...

**Comment by PekkaSavolainen** [comment]
> If we go with the 'please start toolbox again manually' option, we should do it only for Windows, and for Linux we can get back to auto-restart using os.execl.

Sounds like a plan.

**Comment by manuelma** [comment]
I'm surprised though that there's no good way of restarting a python program on Windows?

**Comment by soininen** [comment]
This shouldn't occure anymore since we don't update `spine_items` at Toolbox startup.

**Comment by PekkaSavolainen** [comment]
Yes, I was about to close this one too but @manuelma commented above that he'd like to figure out the reason. The reason for this behavior is probably our usage of Pythons `multiprocessing` package. There are some peculiarities for using it on Windows which we don't take into account. Better to make a new issue about that if needed.
