### ISSUE TITLE
v0.6.0-final.1?

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1412]
Looks like we need a to make a new release-0.6 (final.1) version. The Add/Upgrade SpineOpt wizard in Settings always upgrades SpineOpt to the newest version and I think the newest version is already broken because release-0.6 is shipped with spinedb_api v0.12.1. We need a fixed version of SpineOpt.jl that is compatible with this particular Spine Toolbox (just like we did with release-0.5). @manuelma do we already have a SpineOpt version that is compatible with Spine Toolbox release-0.6?

Also, there's a small but annoying bug in Settings in the resolve Python, Julia, and Gams executables (I can fix this).

FYI @soininen, @jkiviluo

**Comment by manuelma** [comment]
I'm not sure what you mean @PekkaSavolainen 

SpineOpt is independant of spinedb_api. All communication is done through the socket. I think we need to check that SpineInterface is the right version at the socket level. I will work on that soon as part of the change that lifts the type from the parameter value into a new column.

**Comment by PekkaSavolainen** [comment]
Ok, I thought updates to spinedb_api would eventually break release-0.6 compatibility with SpineOpt but maybe the culprit will be SpineInterface then.

So, the latest SpineOpt.jl (0.5.9) should work with release-0.6?

**Comment by manuelma** [comment]
It *should*, yes. You can try running both tools from the SpineOpt plugin to confirm. "Load template" loads the template in all DBs passed as tool arguments, and "Run SpineOpt" needs to DBs as arguments (input, and output, in that order).

**Comment by PekkaSavolainen** [comment]
Ok, thanks for the tip. I'll post an update when I get to it.

**Comment by manuelma** [comment]
A side note: at the moment there's no way of ensuring from toolbox that the user has the right SpineInterface. In the past, when SpineInterface depended on spinedb_api (through PyCall), SpineInterface was able to check for itself, that spinedb_api was the right version.

But now the communication is done through the spine db socket server. This means that if we change the server API, and the user updates spinedb_api *but not* SpineInterface, there will be problems difficult to communicate to the user. The user will probably just see a low-level method error or decoding error, because their SpineInterface doesn't know how to talk to the new spinedb_api socket server.

I believe the solution here is to check versions in the socket communication. That is, we need to send something like a version with every message to the server, so the server can check and respond appropriately. If the version is not what the server expects, it can respond with a known error that the client can catch and convert into a message: "Please update SpineInterface by doing this and that"

**Comment by PekkaSavolainen** [comment]
Thank you @manuelma, I really appreciate the explanation. Your idea for the version check sounds good. Do we have an issue for that already?

**Comment by manuelma** [comment]
No problem @PekkaSavolainen 

We don't have an issue but I plan to work on that today. Will create the issue anyways to keep track.

**Comment by PekkaSavolainen** [comment]
There's already a final.1 and there will be final.2 soon. See changelog for changes when released.
