### ISSUE TITLE
Keyboard shortcuts for executing project

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1416]
Main toolbar is lacking keyboard shortcut for controlling project execution. @manuelma proposed F5 to execute all and Ctrl-F5 to execute selected. How about 'stop execution'?

Reported by @jkiviluo

**Comment by jkiviluo** [comment]
I'm used to pressing F9 to execute (GAMS), but can be something else too. I also do 'executed selected' a lot more than just 'execute', so I wouldn't mind if it has it's own F button (like F8 then). 

In future, I hope we could have those pre-set selections so that you could execute any of them, but maybe that can be a separate story.

**Comment by soininen** [comment]
Checking my IDE, it is Shift-F10 to run and Shift-F9 to debug. I agree it makes sense to have separate keys for 'Execute' and 'Execute selection' instead of adding some modifiers. We should also make sure we don't use those F-keys to something else already.

**Comment by PekkaSavolainen** [comment]
At least F4-F10 are available. Also F2

**Comment by manuelma** [comment]
F2 is kinda globally accepted as 'Edit'.

**Comment by soininen** [comment]
F9 and F8, then?

**Comment by manuelma** [comment]
How about F5, F6, F7 for execute, execute selected and stop?

**Comment by soininen** [comment]
F5, F6 and F7 can now be used to control project execution.
