### ISSUE TITLE
ImportError: cannot import name 'join_value_and_type' from 'spinedb_api.parameter_value'

### ISSUE THREAD

**Issue by jgmonroe1** [Spine-project/Spine-Toolbox#1439]
I just pulled the latest version of the Spine Toolbox and I get the following ImportError:

(spinetoolbox) C:\Users\jgmon\Spine-Toolbox2\Spine-Toolbox>python -m spinetoolbox
Traceback (most recent call last):
  File "C:\Users\jgmon\Anaconda3\envs\spinetoolbox\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\jgmon\Anaconda3\envs\spinetoolbox\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jgmon\Spine-Toolbox2\Spine-Toolbox\spinetoolbox\__main__.py", line 20, in <module>
    from spinetoolbox.main import main
  File "C:\Users\jgmon\Spine-Toolbox2\Spine-Toolbox\spinetoolbox\main.py", line 37, in <module>
    from .ui_main import ToolboxUI
  File "C:\Users\jgmon\Spine-Toolbox2\Spine-Toolbox\spinetoolbox\ui_main.py", line 61, in <module>
    from .spine_db_manager import SpineDBManager
  File "C:\Users\jgmon\Spine-Toolbox2\Spine-Toolbox\spinetoolbox\spine_db_manager.py", line 41, in <module>
    from spinedb_api.parameter_value import join_value_and_type, split_value_and_type
ImportError: cannot import name 'join_value_and_type' from 'spinedb_api.parameter_value' (C:\Users\jgmon\Anaconda3\envs\spinetoolbox\lib\site-packages\spinedb_api\parameter_value.py)

I created a new directory and reinstalled the toolbox then ran it in the command line, where I got the same exact error. I am wondering if anyone else has this same issue.

**Comment by soininen** [comment]
Did you upgrade Toolbox's dependencies? You need to run

```
python -m pip install --upgrade -r requirements.txt
```

every time you pull.

**Comment by jgmonroe1** [comment]
Yes, I ran the command to upgrade the dependencies, I still get the same error.

**Comment by jgmonroe1** [comment]
Update: I created a brand new Anaconda environment and did a clean install of the toolbox, it seems to work fine now. Thanks!

**Comment by manuelma** [comment]
It's not the first time I hear `pip install -U` doesn't work for people. Are we missing something? @ererkka @PekkaSavolainen

**Comment by PekkaSavolainen** [comment]
We are missing the `--upgrade-strategy` option of pip which is used by the `--upgrade` option. The default upgrade strategy is `only-if-needed`, which is IMO the reason why `pip install --upgrade` does not not upgrade a package (sometimes) if the version number has not changed. So, our options are to update the instructions to either use the `--upgrade-strategy` thing or `--force-reinstall`.

**Comment by manuelma** [comment]
Thanks @PekkaSavolainen !

I guess we could update our README with the correct upgrade strategy. Although we're now about to merge (I believe) the branch that uses PyPI. How do we proceed? Does `pipx upgrade` also suffer from the same problem?

**Comment by PekkaSavolainen** [comment]
> I guess we could update our README with the correct upgrade strategy.

I tried `pip install --upgrade --upgrade-strategy eager -r requirements.txt` and there were initially some errors so I'm not sure what the correct upgrade strategy is. In addition to readme.md, the upgrade scripts in toolbox\bin folder should be updated with the same command.

> Does pipx upgrade also suffer from the same problem?

I don't think so because pipx installs spine toolbox from pypi and this problem (should) only concern git cloners.

**Comment by ererkka** [comment]
Hi, If you install Toolbox with `pip(x) install spinetoolbox` or even from a local clone with `pip install -r requirements.txt` it will install DB API, Engine and Items from PyPI, _not the latest from GitHub_. So the user needs to have latest of those other packages installed manually. A solution is to put the VCS urls back to requirements.txt so that a developer will always get the latest of those packages. I can do that.

**Comment by ererkka** [comment]
Another way to look at this is that there is now something new in DB API (right?) which is not published to PyPI.

**Comment by PekkaSavolainen** [comment]
Ok, that clears things up. IMO we should make `pip(x) install spinetoolbox` install everything from PYPI (like it does now of course). This refers to the *Installation for PYPI* section in readme.md. We should put the VCS urls back to requirements.txt, so that devs and git close users can install the latest from GitHub with a single line (pip install -r requirements.txt). This refers to the  *Installation for sources* section in readme.md. I also noticed that the scripts in toolbox/bin (upgrade_spine_engine.py, upgrade_spinedb_api.py, and upgrade_spine_reqs.py) now install from PYPI. The scripts were meant just for devs and git clone users so these should use just the VCS urls.

Come to think of it, isn't this exactly the source of the problem here in this issue and the like? If users have a git clone and they do a `pip install -r requirements.txt --upgrade`, *like we tell them to do in readme.md*, pip will look into PYPI for a new version and then does not upgrade it because there is no new version there.

**Comment by ererkka** [comment]
That’s right, and on hindsight it was a mistake to remove those url’s. On the other hand, someone who develops more than one package has those other packages cloned locally as well. In this case they do not want to install from GitHub again, but use the local clones instead (they might be working on separate branch etc.). But those people should probably be aware of how it works.

**Comment by ererkka** [comment]
Should be fixed now (if tests pass).

**Comment by PekkaSavolainen** [comment]
Thanks @ererkka. Until next time :)
