### ISSUE TITLE
Possible issues with upgrading requirements

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1453]
It seems that `pip upgrade requirements.txt` is not working as we assumed it works, and we'd need an extra switch to force upgrades even when the requirements' versions didn't change. This may or may not be the cause of issues #1451 and #1449 

We need to find out what's wrong and update installation instructions in the README.

**Comment by PekkaSavolainen** [comment]
This problem and a possible solution (using the `--upgrade-strategy` flag) was also discussed in 
https://github.com/Spine-project/Spine-Toolbox/issues/1439

**Comment by PekkaSavolainen** [comment]
FYI @DillonJ, @ererkka, @jkiviluo 

Turns out that the pip --upgrade-strategy option did not work in our case and IMO --force-reinstall is a bit too cumbersome and heavy for everyday use. So the solution is to first uninstall spinedb_api, spine_engine, or spine_items and then reinstall them.

The upgrade process **for our Git users** goes like this. 

1. Pull latest commit for Spine Toolbox
2. `pip install --upgrade -r requirements.txt` in Spine Toolbox repo root
3. Run `bin/upgrade_spine_reqs.bat`

These instructions are now in README.md. In addition, `upgrade_spine_reqs.bat` (or actually `upgrade_spine_reqs.py`) has been updated to first uninstall spine_items, spine_engine, and spine_items and then reinstall all of them one by one from GitHub.

Note that there's no need to pull the latest commit for spine_engine, spinedb_api, or spine_items, if you just want to continue working. 

An alternative is to do this manually: uninstall e.g. spine_engine. pull latest spine_engine, reinstall spine_engine, etc.

Please reopen if I missed something.

**Comment by ererkka** [comment]
Another solution would be to use the `-e/--editable` switch, which seems to always clone the latest commit and install that. (Repo is cloned under *src/* dir by default and installed from there.) Then requirements.txt would then have:

    -e git+https://github.com/Spine-project/Spine-Database-API.git@master#egg=spinedb_api
    -e git+https://github.com/Spine-project/spine-engine.git@master#egg=spine_engine

Pip normally works based on the version numbers: if there is no newer version available there is no need to update. The source of problems here is that our package version numbers have not been bumped even though there has been new features (and possibly deprecation of old stuff) introduced to the code. For example, DB API master has 18 commits after v0.12.2.
