### ISSUE TITLE
Empty relationships no longer greyed out in Spine DB Editor

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1454]
I believe the expected behaviour is that empty relationships should be greyed out in trieview - this appears not to be happening at the moment

![image](https://user-images.githubusercontent.com/7080191/126798376-5358a581-a765-4db4-9626-07241ce0a4ae.png)

**Comment by manuelma** [comment]
It may be better in latest master. Can somebody check and close if satisfactory?

**Comment by manuelma** [comment]
Actually I can't get rid of the 'expand indicator' randomly. It's not a huge deal but it would be very good to manage that as well. So the class is grayed out, but there is the arrow on the left for expanding the childless item.

**Comment by soininen** [comment]
> Actually I can't get rid of the 'expand indicator' randomly.

Can you set the flag for such items to `Qt.ItemNeverHasChildren`? Would that remove the expand arrow?

**Comment by manuelma** [comment]
> Can you add the flag `Qt.ItemNeverHasChildren` for such items? Would that remove the expand arrow?

To clarify, the arrow is correctly removed *sometimes*. It's probably a problem of coordination between the UI thread that paints the arrow, and the DB thread that fetches the items. The UI thread doesn't know whether or not the item has children until some fetching has been done. But we don't want to block the UI during DB fetching because that damages performance too much (and basically defeats the purpose of doing the DB fetching asynchronously).

So the first time the UI calls `hasChildren()`, we return `True` and trigger a DB fetching. At that point the UI paints the arrow (because `hasChildren()` has returned `True`). Then, if as result of fetching we determine that the item has no children, we schedule an update on the view, which calls `hasChildren()` again and should remove the arrow as the result this time will be `False`. This works sometimes, but some other times I think  the view gets updated before `hasChildren()` is able to return `False`.

**Comment by manuelma** [comment]
I found a solution which is to emit layoutChanged whenever the model cannot fetch more for a certain index. This forces a view repaint and the indicator is removed at that point if the class is empty. Closing.

**Comment by manuelma** [comment]
Actually, the previous solution triggered an infinite loop of fetching, damaging performance big time. Now I have implemented another solution which seems to work better. Please reopen if not good.
