### ISSUE TITLE
Problem with Julia persistent console 'restart' option

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1458]
Restart context-menu item in Julia persistent console does not do a complete restart, which results into user having to restart the app after editing a Julia script.

Steps to reproduce:
1. Make a Julia Tool spec with some main program file with a typo e.g. `println("hello world"`.
2. Save and hook the Tool spec to a Tool
3. Make sure you're executing in *Julia* perisistent console by unchecking the Settings -> Tools -> Use Jupyter Console checkbox
4. Execute the Tool and note that the execution fails (as it should because of the typo)
5. Go to Tool spec editor and fix the typo. Save
6. Execute again and note that it still fails because it uses the previous code. This is ok.
7. Click `restart` from Julia persistent console context-menu.
8. Execute again and note that it still fails. Not ok.

Expected result:
Clicking `restart`, should do a full restart and not just clear the console.

Even after opening another project and then going back to the previous one does not change the outcome. Users now need to restart the app to make changes in Julia scripts 'stick'.

**Comment by manuelma** [comment]
Will fix.

**Comment by manuelma** [comment]
The issue here is not with the restarting, but with the current working directory. We aren't updating the working directory for each execution, so the tool is always using the file from the first execution (the one with the syntax error). Step number 6 is not ok after all. After fixing the script, the execution should work immediately, without a need for restarting.

I will fix this now.

**Comment by PekkaSavolainen** [comment]
You're right, works like a charm again. I actually fixed the same bug on Python side but did not check if the same thing happens on Julia. Restart works just fine. Thanks.
