### ISSUE TITLE
Crash with Tool spec editor

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1470]
I was changing Tool specification settings (added two new input data files). After that, I pressed Ctrl-S and got this:

```
Traceback (most recent call last):
  File "C:\data\SpineToolbox\spinetoolbox\widgets\notification.py", line 272, in _push_notification
    if self._settings.value(self._settings_key, default="2") != "2":
RuntimeError: Internal C++ object (PySide2.QtCore.QSettings) already deleted.

Process finished with exit code 1
```

**Comment by jkiviluo** [comment]
I remember something like this happening to me before when working with the Tool spec editor. Maybe even multiple times.

**Comment by jkiviluo** [comment]
Got it again. Very similar situation. I was editing output file names. (Changed one name and added one new name).

**Comment by manuelma** [comment]
I wonder if Qt would delete a QSettings object after a second one has been created with same parameters? Because we are indeed doing that in the constructor of our `CustomQGraphicsView`.

**Comment by jkiviluo** [comment]
> And you didn't press Ctrl+S this time?
Can't remember for sure, but probably I did press it.

**Comment by PekkaSavolainen** [comment]
Tried reproducing with a Python Tool spec but did not succeed (no traceback). @manuelma do you have a hunch on how to reproduce this? @jkiviluo could you paste the Tool spec JSON file contents here, please?

**Comment by manuelma** [comment]
The traceback is quite clear, the QSettings object we create in the constructor of ToolboxUI has been deleted for some reason. I can't see any reason for this to happen other than Qt internally deleting the object after a second QSettings is created with same arguments (organization, application). So my idea for a fix is to stop creating the second QSettings (it happens in the constructor of CustomGraphicsView) and instead using the QSettings created in ToolboxUI.

Of course this is a long shot and might do nothing, but trying to reproduce the error seems difficult (it only happens every so often).

**Comment by manuelma** [comment]
I just pushed my "fix". Let's see if it helps, I'm not very optimistic but at least it can help discarding my above suspicion.

**Comment by soininen** [comment]
I'm quickly skimming through these threads to get myself back on track with Toolbox so this might be just noise; did @jkiviluo catch this Traceback while debugging in PyCharm? Because in that case, PyCharm forcefully kills Toolbox immediately it encounters an uncaught exception which in this case is the `IndexError` (if I connected the Slack thread here correctly). Such forceful killing may very well have produced the `internal C++ object already deleted` thing. I see this quite often while debugging stuff in PyCharm.

**Comment by manuelma** [comment]
Thank you @soininen that makes a lot of sense. You just saved us from doing a whole bunch of senseless refactoring.

That `internal C++ object already deleted` is then caused by a signal firing *after* the `ToolboxUi` and all its children have been deleted. So we don't have a crash here. The only thing to check is whether or not my 'fix' solves the first `IndexError`, and if yes then we can just close.

**Comment by jkiviluo** [comment]
I was having a crash without PyCharm and then I switched to PyCharm to get the traceback (because the whole Python console crashed). However, now things seem to work both with and without PyCharm.

**Comment by manuelma** [comment]
On Linux, the `IndexError` appeared every time one saved the spec, but never led to a crash. Is this a windows thing? If my commit above fixed it, I think we can checkout the commit just before and do any modification to a spec followed by a save, and see if toolbox crashes on windows.

**Comment by PekkaSavolainen** [comment]
I never saw the IndexError.

**Comment by manuelma** [comment]
> I never saw the IndexError.

Did you have other specs than Tool specs in the project? You may try creating dummy Importer, Exporter, DT specs, even installing the SpineOpt plugin, and try again.

**Comment by jkiviluo** [comment]
I use to see lot of IndexErrors, but haven't seen them anymore (I haven't been using Toolbox too much in past few days).

**Comment by jkiviluo** [comment]
I think we can close this. Seems to work fine now.
