### ISSUE TITLE
Tool spec cannot be transferred due to absolute location of python.exe

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1472]
I got a new laptop and moved my Spine project folders from the old laptop to the new one. I installed my Python in new conda environment with a new location. I can find this new location in Spine Toolbox settings just fine. However, tool spec in a project from the old machine has this:

```
    "execution_settings": {
        "env": "",
        "kernel_spec_name": "spi37",
        "use_jupyter_console": true,
        "executable": "C:\\Users\\prokjt\\.julia\\conda\\3\\envs\\spi37\\python.exe"
    }
```

The tool spec editor does not allow to change that. That would be the least we can do, but we should really give the user a hint to locate missing executables for the kernel/consoles when they cannot be found. 

I suppose you can reproduce this just by closing Toolbox. Use text editor to edit the executable location in the tool spec to point to a wrong folder. Re-start Toolbox. Try to modify the Tool spec in any way and save.

**Comment by PekkaSavolainen** [comment]
> The tool spec editor does not allow to change that. That would be the least we can do, but we should really give the user a hint to locate missing executables for the kernel/consoles when they cannot be found.

You can change the interpreter when you click on the *Basic Console* radiobutton. But in this case it does not matter what you have in the grayed-out 'interpreter' line-edit because for this tool spec you have selected to use the *Jupyter Console* and a kernel spec called *spi37*. You can find the interpreter that *spi37* uses by opening the kernel spec editor or by opening its kernel.json file from the kernel spec editors context-menu. I don't think Jupyter kernel specs are meant to be shared or relocated like you just had to with the new laptop because Jupyter uses absolute paths in kernel specs. You just need to recreate the kernel spec *spi37* or edit the kernel.json file yourself.

**Comment by manuelma** [comment]
We discussed at some point about generating a sort of `requirements.txt` file that would travel with the project and would allow the target machine to recreate any python environment.

Are there any plans on implementing that idea? That could save our users quite a headache to figure out all those details @PekkaSavolainen outlines above.

**Comment by manuelma** [comment]
Also, I think the UI could make more clear that the interpreter line edit only applies to the case where Basic console is selected, and the kernel spec combobox only applies to the opposite case. Graying out stuff is good, but we could place the widgets differently maybe? I'm not sure, but it looks like the above wasn't immediately clear to @jkiviluo ?

**Comment by jkiviluo** [comment]
Could be that I didn't see how to use it correctly, but I think I tried all combinations. Of course that is not very useful when the problem is not re-producible, so let's assume that it's fine unless it pops up again. Meanwhile, the dialog would benefit from better organization of the choices.

**Comment by jkiviluo** [comment]
Closing this until the problem emerges again. Hope not.
