### ISSUE TITLE
Cannot move middle horizontal boundary in the main view

### ISSUE THREAD

**Issue by ererkka** [Spine-project/Spine-Toolbox#1473]
Bringing the cursor to the border which separates Project, Design View and Properties widgets from Event Log, Execution Log and Console it turns to a resize cursor. The border cannot be moved, however.

**Comment by PekkaSavolainen** [comment]
Happens with the 'factory' settings, right? This has been a problem ever since #1297. See my comment https://github.com/Spine-project/Spine-Toolbox/issues/1297#issuecomment-800094379

But there's a workaround. If you reposition the dock widgets like this.

![issue_1473_dockwidget_positioning](https://user-images.githubusercontent.com/43600314/131847751-a4ae5798-1574-43a0-93b5-67fbf99644cb.png)

The border should move again. Still, something should be done about this.

**Comment by ererkka** [comment]
Happens with default layout (haven’t moved anything), yes. I tried the layout you propsed, but still can’t move that horizontal boudary.

![image](https://user-images.githubusercontent.com/10612239/131969451-28b243c9-a051-4964-98e4-0a81e4d428ac.png)

**Comment by manuelma** [comment]
Can anybody check if the above commit helps with this?

**Comment by PekkaSavolainen** [comment]
No. This is how Spine Toolbox looks for new users now and the dragbar (or whatever the thing inside the black ellipsis is) does not move at all. 

![issue_1473_main_window_default_geometry](https://user-images.githubusercontent.com/43600314/134544578-3893ca02-f321-4d6b-92fa-1e6a7a039597.png)

I think we can make it look a bit nicer than that.

**Comment by manuelma** [comment]
Might be a windows thing? Anyways, I agree we can make it look nicer. I think that commit helps in some cases... What it does is it sets the minimum size to zero for all dockwidgets after every layout change, so they can be arbitrarily shrunk. Maybe what it's missing is setting the right size policy to go along?


Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by PekkaSavolainen** [comment]
Yes I saw what you did with the dockwidget sizes. It's a good improvement, nice work.

**Comment by manuelma** [comment]
Thank you. It really made a lot of sense and solved the issue in my system, but I should have checked on windows before pushing... Anyways I will fix this asap.

**Comment by PekkaSavolainen** [comment]
One way to manually make the vertical splitter (dragbar) work again, is to move all dock widgets under the Design View. The end result looks exactly the same but the splitter works from then on.

**Comment by manuelma** [comment]
I did something new. It's kind of @PekkaSavolainen 's workaround above, but programmatically. Hope it helps.

**Comment by PekkaSavolainen** [comment]
You got it! great work. However, there was a noticeable flicker while it reshuffled the dock widgets before showing the main window in its final form. I removed the flickering by removing line `dock.setFloating(True)` as seen in commit above. I also removed the raise_() line because I did not know what that was for. Hope it was not necessary :)

**Comment by manuelma** [comment]
OK cool ! I was going to check if floating the docks before placing them was really needed, guess it's not?
The raise_() was so event log tab is active in the factory layout. Without it, I think item log tab is active instead. Not a big deal I guess.

**Comment by PekkaSavolainen** [comment]
whoops, in that case I'll put the _raise back. New users won't see the welcome message without it.
