### ISSUE TITLE
Time pattern documentation could be improved with more information about accepted syntax

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1487]
The time pattern functionality is described under the Parameter Value Editor section here:
https://spine-toolbox.readthedocs.io/en/latest/parameter_value_editor.html

However, it is missing information about what syntax and symbols you can use. 

Edit: also, the default text in the Time pattern editor appears to contradict the documentation in terms of the expected format. For example, the code "d" appends the numeric value and is lower case in the default and is upper case and prefixes the value in the documentation

**Comment by soininen** [comment]
That editor and its documentation certainly need some improvements. In the meantime, you can check the syntax and symbols from spinedb_api's documentaion:

https://github.com/Spine-project/Spine-Database-API/blob/master/docs/source/parameter_value_format.rst#time-pattern

It's not ideal since it describes the JSON format but hopefully helps until we get the editor's documentation up to speed.

**Comment by soininen** [comment]
The correct time period format is now included in Toolbox documentation and Time pattern editor's UI provides a link to that. Also, the initial value on the editor has been fixed.
