### ISSUE TITLE
Pasting of timeseries data into parameter value editor is slow

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1537]
Pasting 8760 values from excel into parameter value editor widget of toolbox (fixed resolution) takes 1m10s

Feels like it could be faster. Is there something easy we could do to improve performance?

**Comment by soininen** [comment]
We select the table cells that contain the pasted data after the operation is completed. The selection was done cell-by-cell which turns out to be very VERY inefficient. The selection is now done as a block which is lightning fast compared to the previous method. Hopefully pasting into the value editor feels a bit snappier now.

**Comment by DillonJ** [comment]
Thanks @soininen... just tested this - wow - instantaneous for me - that's really great!
