### ISSUE TITLE
Julia console output is difficult to read.

### ISSUE THREAD

**Issue by Tasqu** [Spine-project/Spine-Toolbox#1660]
Not sure why, but using the `Basic Console` option for Julia through Toolbox prints the output in a very hard to read colouring:

![image](https://user-images.githubusercontent.com/77660814/157181168-37740001-797a-4386-901b-37809bda60e7.png)

**Comment by manuelma** [comment]
<img width="807" alt="Capture" src="https://user-images.githubusercontent.com/11472756/157184549-98d4fd39-6708-4a13-8a94-a7d194db15d5.PNG">

Can't reproduce, see above. I wonder what's going on, are you on windows? Do you have any system theme active? Do others experience the same issue?

**Comment by Tasqu** [comment]
@manuelma on Windows, yes. No system level theme's should be installed, as I don't know what those are 😄. If it's just me, it could be related to the environment I'm running toolbox in? I wouldn't be surprised if the `IJulia` packages that come with JupyterLab have messed with the standard console in some way.

**Comment by manuelma** [comment]
But if you open julia from outside toolbox, you get the right colors right? Because at the moment what toolbox does is basically that, open julia and then forward the output including colors. Maybe I'm missing something though, could be that we need to set a default color somewhere - because the only problem is you get black when you should get white, everything else seems to be ok. Which Qt/Pyside2 version are you using (should appear when you run pip freeze or equivalent)?

**Comment by Tasqu** [comment]
Yeah, I get the right colours outside toolbox, `QtPy = 2.0.1`, `PySide2 = 5.14.2.3`

**Comment by manuelma** [comment]
What about the python console, do you also get the wrong colors?

**Comment by PekkaSavolainen** [comment]
Confirmed on a fresh Python 3.8 conda env. This is not about JupyterLab. On my system, the Python console looks exactly the same as in @Tasqu's pic above. Interestingly, this does not happen on a non-conda Python (the text is white there). The reason is somehow related to the pygments style that we set in [this line](https://github.com/Spine-project/Spine-Toolbox/blob/master/spinetoolbox/widgets/persistent_console_widget.py#L58). I wonder why&how this works on Linux because we first set the background and foreground (text) colors for the console widget using pygments and then we give another styling command to Julia REPL with the --color=yes argument. It looks like the --color=yes argument is just ignored on windows. The easy fix here seems to be to use some other pygments style. For example, 'solarized-light' looks pretty cool. Also 'inkpot' seems to work if we want to stick with the dark backrground.

**Comment by manuelma** [comment]
My screenshot above is from windows (need to check my env details). On Linux I get something similarly nice. I dont think color=yes is ignored on win, otherwise we wouldn't have any output highlighting.  Note that we do a combination of things to highlight text in the console, pygments only is used for the stdin - stdout and stderr are colored by parsing the ansi escape codes that come from julia when color=yes.
I will try to reproduce using the fresh conda 3.8 env and should be able to fix from there.

**Comment by PekkaSavolainen** [comment]
Ok, I see. Thanks for the clarification @manuelma. My next idea was to change the encoding of cmd.exe from cp1252 (default) to utf-8 but that doesn't seem to have any effect either. How do you start the app on windows? Using cmd.exe or powershell?

**Comment by manuelma** [comment]
I think the encoding is fine, the escape codes seem to be reaching the console widget properly. I suspect the issue is `self._style.styles[Token.Text]`  is returning a dark color in some setups, instead of the whitish color I would expect. See how we use it here:

https://github.com/Spine-project/Spine-Toolbox/blob/a7fdcd730a38bcff189e94c9ba16b4d2f653f18a/spinetoolbox/widgets/persistent_console_widget.py#L60

@PekkaSavolainen do I understand correctly that you have managed to both get the wrong and right highlighting in two different python envs? are there any differences between the pygment versions between the two? Can you add something like `print(foreground_color)` in the __init__ method of the persistent console widget to see what color is actually using?

**Comment by PekkaSavolainen** [comment]
This is the Julia Console on non-conda python 3.8 (pygments 2.10.0)

![issue1660_basic_console_not_conda](https://user-images.githubusercontent.com/43600314/157642494-2bb512c1-c778-49fc-81cf-58a785cb4b5f.png)

This is it on conda python 3.8 (pygments 2.11.2)

![issue1660_basic_console_conda](https://user-images.githubusercontent.com/43600314/157642818-16647cca-878b-40b3-872e-1abd2214838c.png)

After upgrading the outdated pygments, my non-conda toolbox julia console looks like the lower picture as well. Never seen the correct colors in toolbox julia console, (note that in the upper picture, the Julia bubbles in the banner are not colored).

**Comment by PekkaSavolainen** [comment]
foreground_color is an empty string!

**Comment by manuelma** [comment]
Thank you @PekkaSavolainen 

So none of your screenshots look exactly like @Tasqu 's original, @Tasqu is getting syntax highlighting for the stdout and stderr (see the word Activating in green for example).

So it looks like in your case, indeed, --color=yes is not working.

> foreground_color is an empty string!

in which case? I feel like in the one at the top it shouldn't be empty.

**Comment by PekkaSavolainen** [comment]
On pygments 2.11.2 monokai style Text.Token is an empty string, i.e. foreground_color is an empty string. I'm sure it was not an empty string on the older pygments version. You're right, my colors are not exactly as in @Tasqu's og pic, but I'm pretty sure this is related, since the dark text looks the same.

**Comment by manuelma** [comment]
Yeah, we discovered two issues here:
- The foreground color being dark instead of bright
- julia --color=yes not working in any of @PekkaSavolainen 's setups

But I don't think they are related, they look separate to me. We need to absolutely fix the foreground color issue (I don't think colored output is that critical, just very nice to have)

**Comment by manuelma** [comment]
Monokai's Text.Token is #f8f8f2 in Pygments==2.10.0

**Comment by manuelma** [comment]
The above commit fixes the foreground color issue I think, I tested it with Pygments 2.10.0 and 2.11.2.

The second issue about --color=yes apparently not working needs more thought, I will leave that one to you @PekkaSavolainen :)

**Comment by manuelma** [comment]
See https://github.com/Spine-project/Spine-Toolbox/issues/1662

**Comment by PekkaSavolainen** [comment]
Yes, the text (foreground) color problem is fixed.
