### ISSUE TITLE
Exporter output file

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1692]
The Exporter design is a bit awkward in that it doesn't allow the user to select the output file location, the file is always in the Exporter's output folder. 

I wonder, would it make sense to change the Exporter so it writes to a file in a Data Connection?

@soininen @jkiviluo what do you think?

With this, we could have two Exporters writing to the same excel file, in different sheets. It would also look more symmetrical with respect to the Importer.

**Comment by soininen** [comment]
Having the output files (also for Tool) in a fixed location might be useful e.g. when one wants to report some results for later analysis. There are some things we need to consider, though:

- I'm not particularly fond of the idea of forcing Data Connection after every exporter so the current behavior should be the default.
- How should we deal with scenario/tool filters and parallel Exporters? They cannot all be writing to the same file simultaneously.

**Comment by manuelma** [comment]
Thanks @soininen 

> I'm not particularly fond of the idea of forcing Data Connection after every exporter so the current behavior should be the default.

May I ask why specifically? How about forcing DC before each Importer? Can we get rid of that too? I feel there's an imbalance here that we could be handling better...

**Comment by soininen** [comment]
> May I ask why specifically? How about forcing DC before each Importer? Can we get rid of that too? I feel there's an imbalance here that we could be handling better...

I fail to see the imbalance here. The usual use case I see Exporters being used is when the output files are directly fed to a successor Tool and in this case users don't really need to see exported files unless it's for debugging purpose. A DC in between would be an overkill, I think, and in case of parallel execution would just complicate things unless we find some really nice way to handle it.

I also forgot to mention the case of e.g. multiple CSV files above where you write a new file for each exported table. You don't know what the final output files are until the export has been finished. This may not work well if the file names were forced by DC.

Also, if such 'balance' between Importers and Exporters is required we should also consider Tool as an Exporter or as an item that produces output files. Do we want to add a DC after each Tool that has file outputs? I don't think we do.

Maybe we could make a specific project item to merge files? This would allow merging files from Exporters, Tools and Data Connections all in one; perhaps support parallel execution in a sane way, too?

**Comment by manuelma** [comment]
Thanks! I guess I agree on almost everything except that the usual use case for Exporters is passing the result to a Tool. I don't find that useful and in my experience what the user wants is just access the exported file and look, and in the case of excel, implement some additional postprocessing in place. But now I realize it wasn't designed with that in mind. Just wondering if we could make it better/more useful to more users.

**Comment by manuelma** [comment]
> Do we want to add a DC after each Tool that has file outputs? 

I don't dislike this at all as an option. The way tool output files are buried within the Tool data directory has always seem pretty obscure to me and I believe other users too.

**Comment by soininen** [comment]
I, on the other hand, frequently see Exporters feeding files to Tools and Importers in real-life workflows. I guess it is not so common if you're using SpineOpt since it deals directly with Spine databases :)

Anyway, I'd be happy if we found ways to expose the outputs/result files in a more user-friendly ways than having to dig into some hashed folders with obscure `.filer_id` files though I doubt DC is the ideal solution here since it's geared more towards fixed file locations/names/URLs but I can be proven wrong. I just feel something like specific project items for file merging and output file viewing might be a better solution.

**Comment by jkiviluo** [comment]
I think we should have different use cases in mind when doing changes like this.

I like Antti's viewpoint on DC as the intializer and then something like a file viewers as a terminus. However, 'file viewer' is too restrictive, since there can be other reasons (outside of Toolbox) to end up in file. 

My intuition would be that we could either 1) let exporter itself define the behavior - it could require a file location and that could then give then the option to use sheets (or files in case of csv) as one dimension in the mappings or 2) let the following item dictate what happens - if it's a DC, then dump alternatives in sheets (or separate csvs), but it it's a tool, then keep things parallel. The first option sounds better right now.

We also have lot of workflows depending on specific behavior, so we need to be careful about this.

**Comment by manuelma** [comment]
I think we should at least be able to select the Exporter output file with a file dialog. Something similar to the SQLite file for the new Spine DB in the Data Store item, where the default is a file in the data directory.

One problem is the Output file/label ambiguity. I feel I have complained about this before and you have explained it to me, but I still don't fully understand it. I couldn't find any documentation. @soininen would it be possible for you to briefly describe, whenever you get the chance (and maybe once again), when the label applies and when the output file applies?

**Comment by soininen** [comment]
> when the label applies and when the output file applies?

Exporter exports data as "tables" which translates into workbook sheets in Excel, database tables in SQL or domains/sets/parameters in .gdx. CSV, on the other hand, does not inherently support "tables" but we can export each table into a separate file named after the table itself. Based on that the output can be summarized as follow:

- If output format can contain multiple "tables": single file, use label as file name
- If output format doesn't support "tables" but there is only a single unnamed table to export: single file, use label as file name
- Else:  multiple files named after "table" names, use label as resource label

I think users should be able choose output directory instead of a single file to support multiple output files as well as scenario/tool filters. In case of filters we need to organize the output files somehow, e.g. into subdirectories named after filter_id but keeping in mind the path length restrictions on Windows.

**Comment by soininen** [comment]
I'd also like to bring another point into consideration: should we restrict the output within the project directory only? I feel we may be shooting ourselves in the foot if we allow an arbitrary output directory here. There are compelling reasons to keep the project self contained and free of hard coded absolute paths.

- Remote engine execution: how do we deal with situation where exporter writes into a random directory on the remote machine?
- Shared projects (by git repository or similar): one cannot expect all users to have exactly the same directory structure on their systems.

**Comment by manuelma** [comment]
Thank you so much for the prompt response @soininen !

**Comment by manuelma** [comment]
Thinking more into it, I feel we should keep the Exporter as it is and don't allow the user the select the ouput file/folder. We modelled Exporter after Tool so to say, rather than as a mirror of Importer, and I think that's fine. I'd just need to recalibrate my expectations. Which means, I should pass the result of the Exporter to a Tool that does the extra post-processing I need.

**Comment by manuelma** [comment]
But we should deal better with the ambiguity between label and file. Maybe implement the necessary `if else` stuff from @soininen 's bullet points and adapt the UI to the situation, so the user knows what's happening.

**Comment by manuelma** [comment]
Maybe we can continue the discussion in https://github.com/Spine-project/Spine-Toolbox/issues/1696 - will close this one.
