### ISSUE TITLE
Importer imports None after empty data columns

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1780]
When I have empty data columns in an importer, the data becomes None and will be None also for later columns that have actual data. May be just Excel importing (or may not be).

Base alternative selected in the DB editor snapshot:
![image](https://user-images.githubusercontent.com/40472544/192804427-9140f36a-0635-48ae-874e-5bfaf5128447.png)

**Comment by soininen** [comment]
It doens't look like the empty columns are the culprit here. What seems to happen in this case is that some of those parameter values are imported also from another table (connection_p) as Map values and the second table overwrites the imports from the first. I think the real bug here is that a Map without values is imported as a null. Instead, we shouldn't import it at all.

**Comment by soininen** [comment]
Fixed in Spine-project/Spine-Database-API@38e1676. Sorry for the wrong reference in the commit message. @jkiviluo can you please check the Excel imports works now?

**Comment by jkiviluo** [comment]
Seems to be working correctly. Closing...
