### ISSUE TITLE
spine-items unit tests fail on windows

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1806]
Testing write order stuff doesn't usually pass.

```
Failure
Traceback (most recent call last):
  File "spine-items\tests\merger\test_MergerExecutable.py", line 175, in test_write_order
    self.assertTrue(merger2_idx < merger1_idx)
AssertionError: False is not true
```

**Comment by soininen** [comment]
Turns out we never initialized `_ordering_manager` because there never was a "MainProcess". I think I got that fixed but the test still fails for some other reason.

**Comment by soininen** [comment]
@manuelma kindly fixed the write order test but `TestDataConnection.test_add_file_references()` still fails. Also, one of the View tests ends in an endless loop.

**Comment by manuelma** [comment]
I had missed the default start method for multiprocessing processes on windows being 'spawn' (and not 'fork' as on linux). This is a very important difference that I need to pay attention to in the future, because spawned processes don't inherit the state of the parent process as forked processes do. So if one initializes a global variable in the parent process, the spawned children won't be able to see it.

With spawn, the only way of sharing state between processes is with Listener and Client from the multiprocessing.connection module.

Thanks @soininen for the heads up.

**Comment by manuelma** [comment]
Of course, another option is to create something like a multiprocessing.Queue in the parent process and then pass it explicitely to the child processes that need to interact with the ordering manager, but that seems too invasive. At the moment we manage without that - so any child process that imports the spine_db_server module is automatically able to communicate. But we might consider the alternative approach in the future.

**Comment by soininen** [comment]
So it's forking that allowed Linux processes to "share" a state! I was wondering how the db server could ever work. Thanks a lot for the explanation @manuelma

**Comment by soininen** [comment]
Fixed the failing test.
