### ISSUE TITLE
Parameter value tables in Database editor don't always update after purge

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1834]
The object and relationship parameter value tables don't always update their contents when I purge parameter value data from the database. The behavior may depend on the number of values as I don't remember seeing this happen on small databases but now that I have a largish database, I get the behavior consistently.

**Comment by soininen** [comment]
This is actually a more general issue with fetching data in chunks: if we delete data that has not yet been fetched, the fetch iterators will return that deleted data still. Resetting fetching, on the other hand, will duplicate items in the views unless we clear the views as well.

**Comment by manuelma** [comment]
I think we need a way more general approach. The current design is a monster made of, on one hand, synchronous data fetching remainders from the old days and, on the other hand, asynchronous fetching from the db introduced in more recent times. In the old design, we trusted the cache 100% because it was fully populated at the moment we made the DB connection. Then we introduced incremental loading and did our best to resolve conflicts between cache and DB, but sometimes it seems impossible to do so as illustrated by this issue.

Also, we have a bit of redundant code from never unifying the old approach (synchronous fetching) and the new approach (incremental fetching). We have patched the thing multiple times, addressing specific bugs with something that seems to solve it, but the code is getting harder and harder to read. I think we need to rethink the SpineDBManager a bit? I'm not saying we are super far from a nice solution and the current system works quite well - I'm just saying we might wanna rethink things a bit more?

**Comment by manuelma** [comment]
Maybe all we need to do is trust the cache more than the new data coming from the DB (as queried by new fetch parents that need the same data as collected by older parents). So instead of always overwritting the cache with the new data incoming, we keep the data from the cache. And we also keep a collection of removed ids per db and table, and when those specific items are being fetched by the new parents, we simply disregard them?

**Comment by soininen** [comment]
>  So instead of always overwritting the cache with the new data incoming, we keep the data from the cache. And we also keep a collection of removed ids, so when those items are being fetched by the new parents, we can simply disregard them?

I'm currently experimenting with these ideas.
