### ISSUE TITLE
opening the getting_started.html fails

### ISSUE THREAD

**Issue by huckebrink** [Spine-project/Spine-Toolbox#8]
After following the installation instructions and starting Spine-Toolbox, I clicked on the "Getting Started" guide in the Event Log.

This unfortunately fails, yielding this message in the Event Log: 
`[16-11-2020 12:51:16] Opening path [...]\Spine-Toolbox\docs\build\html\getting_started.html failed`

and this message in the terminal:
`ShellExecute 'file:///[...]Spine-Toolbox%5Cdocs%5Cbuild%5Chtml%5Cgetting_started.html' failed (error 2).`

I'm running Windows 10, 64 bit, and Python 3.7.9, on the latest master branch.

The folder `docs/build` does not exists. I've also tried to `python setup.py install` but that didn't help either. 
Any suggestions?

After having installed the dev-requirements.txt and ran make html in the docs directory, it seems to work.
Is this the intended behavior?

**Comment by PekkaSavolainen** [comment]
No, this is not really the intended behavior. As you noticed, the docs only appear to `docs/build` directory when users first build the documentation. Nowadays, the latest User Guide (and the Getting Started section) is also available online in `https://spine-toolbox.readthedocs.io/en/latest/`. We should update the link in Event Log to open this page instead of the possibly non-existing user guide under the `docs/build` folder.

Thanks for reporting.

**Comment by PekkaSavolainen** [comment]
All User Guide and Getting Started links in the app now open the docs from readthedocs.io.
